import test from 'node:test';
import assert from 'node:assert/strict';
import { Weapon } from '../src/game/weapon.js';
import { World } from '../src/world/world.js';
import { Mission } from '../src/game/mission.js';
import { segmentPointDistance } from '../src/core/math.js';
import { mat4 } from '../src/render/math3d.js';
import { Soldier } from '../src/game/actors.js';
import { GrenadeSystem } from '../src/game/grenade.js';
import { BattleDirector } from '../src/game/battle-director.js';
import { ObjLoader, parseMtl } from '../src/assets/obj-loader.js';
import fs from 'node:fs/promises';

test('weapon enforces cadence, ammo, and reload transfer',()=>{const w=new Weapon({magazine:3,reserve:4,fireDelay:100,reloadMs:500});assert.equal(w.shoot(0),true);assert.equal(w.shoot(50),false);assert.equal(w.shoot(100),true);assert.equal(w.reload(150),true);assert.equal(w.update(649),false);assert.equal(w.update(650),true);assert.deepEqual([w.mag,w.reserve],[3,2]);});
test('world blocks walls and permits open cells',()=>{const world=new World(['111','1P1','101','111']);assert.equal(world.canMove(96,96,10),true);assert.equal(world.canMove(60,96,10),false);assert.equal(world.lineOfSight({x:96,y:96},{x:96,y:160}),true);});
test('navigation chooses a walkable next tile around cover',()=>{const world=new World(['11111','1P101','10001','11111']);const step=world.nextStep({x:96,y:96},{x:224,y:96});assert.deepEqual(step,{x:96,y:160});});
test('mission advances through checkpoint, combat, and radio',()=>{const m=new Mission({x:10,y:0},{x:20,y:0}),p={x:10,y:0},enemies=[{alive:true}];assert.equal(m.update(p,enemies),'checkpoint');assert.equal(m.phase,1);enemies[0].alive=false;assert.equal(m.update(p,enemies),'clear');p.x=20;assert.equal(m.update(p,enemies),'complete');assert.equal(m.complete,true);});
test('shot geometry detects targets on aim line',()=>{assert.equal(segmentPointDistance({x:0,y:0},{x:100,y:0},{x:50,y:4}),4);assert.equal(segmentPointDistance({x:0,y:0},{x:100,y:0},{x:150,y:0}),50);});
test('3D matrix composition preserves translation and scale',()=>{const model=mat4.trs(3,2,1,2,3,4);assert.deepEqual([model[0],model[5],model[10],model[12],model[13],model[14]],[2,3,4,3,2,1]);const result=mat4.multiply(mat4.identity(),model);result.forEach((value,index)=>assert.ok(Math.abs(value-model[index])<1e-7));});
test('weapon exposes a stable reload animation timeline',()=>{const w=new Weapon({magazine:3,reserve:3,fireDelay:100,reloadMs:1000});w.shoot(0);w.reload(100);assert.equal(w.reloadProgress(100),0);assert.equal(w.reloadProgress(600),.5);w.update(1100);assert.equal(w.reloadProgress(1100),0);});
test('enemy selects cover instead of charging directly at player',()=>{const world=new World(['111111','1P0001','100001','1000E1','111111']),enemy=new Soldier(world.spawns.E[0]),player={...world.spawns.P[0]};enemy.tacticTimer=0;enemy.update(.1,world,player,100,[]);assert.ok(enemy.cover);assert.equal(enemy.state,'MOVE_TO_COVER');assert.notDeepEqual(enemy.cover,player);});
test('grenade bounces on walls, warns AI, and applies radial damage',()=>{const world=new World(['11111','1P0E1','11111']),player={...world.spawns.P[0],angle:0,alive:true,health:100,damage(n){this.health-=n;}},enemy=new Soldier(world.spawns.E[0]),grenades=new GrenadeSystem();assert.equal(grenades.throw(player,0),true);let exploded=false;for(let i=0;i<180;i++)grenades.update(1/60,world,[enemy],player,()=>exploded=true);assert.equal(exploded,true);assert.ok(enemy.health<75);assert.equal(grenades.active.length,0);});
test('battle director activates reinforcement groups without replacing individual AI',()=>{const enemies=Array.from({length:12},(_,i)=>({alive:true,x:600+i*10,y:600})),audio={ambience(){}},director=new BattleDirector(enemies,audio);assert.equal(enemies.filter(e=>e.active).length,4);enemies.slice(0,4).forEach(e=>e.alive=false);director.update(6,{x:0,y:0},{phase:1,complete:false},{lineOfSight:()=>false});assert.equal(enemies.filter(e=>e.active).length,8);});
test('text-only OBJ assets load with meshes, normals, and MTL colors',async()=>{const [obj,mtl]=await Promise.all([fs.readFile('assets/models/m1-carbine.obj','utf8'),fs.readFile('assets/models/m1-carbine.mtl','utf8')]),asset=new ObjLoader().parse(obj,parseMtl(mtl));assert.equal(asset.meshes.length,3);assert.ok(asset.meshes.every(mesh=>mesh.positions.length>30&&mesh.normals.length===mesh.positions.length));});
